// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVentasBienes.Context;

#nullable disable

namespace SistemaVentasBienes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221202132712_Fix class cliente telefono")]
    partial class Fixclassclientetelefono
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SistemaVentasBienes.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Cliente"), 1L, 1);

                    b.Property<string>("Correo_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dir_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Cliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telefono_Cliente")
                        .HasColumnType("bigint");

                    b.HasKey("Id_Cliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Condicion", b =>
                {
                    b.Property<int>("Id_Condicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Condicion"), 1L, 1);

                    b.Property<string>("Desc_Condicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Condicion");

                    b.ToTable("Condicion");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Forma_Pago", b =>
                {
                    b.Property<int>("Id_Forma_Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Forma_Pago"), 1L, 1);

                    b.Property<string>("Desc_Forma_Pago")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Forma_Pago");

                    b.ToTable("Forma_Pago");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Inmueble", b =>
                {
                    b.Property<int>("Id_Inmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Inmueble"), 1L, 1);

                    b.Property<decimal>("Costo_Inmueble")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Desc_Inmueble")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoInmuebleId")
                        .HasColumnType("int");

                    b.Property<string>("Ubic_Inmueble")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Inmueble");

                    b.HasIndex("TipoInmuebleId");

                    b.ToTable("Inmueble");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Tipo_Inmueble", b =>
                {
                    b.Property<int>("Id_Tipo_Inmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Tipo_Inmueble"), 1L, 1);

                    b.Property<string>("Desc_Condicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Tipo_Inmueble");

                    b.ToTable("Tipo_Inmueble");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Venta", b =>
                {
                    b.Property<int>("Id_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Venta"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CondicionId")
                        .HasColumnType("int");

                    b.Property<string>("Desc_Venta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Venta")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagoId")
                        .HasColumnType("int");

                    b.Property<int?>("Forma_PagoId_Forma_Pago")
                        .HasColumnType("int");

                    b.Property<int>("InmuebleId")
                        .HasColumnType("int");

                    b.Property<int?>("InmuebleId_Inmueble")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_General")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Total_Iva")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Total_Venta")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id_Venta");

                    b.HasIndex("CondicionId");

                    b.HasIndex("Forma_PagoId_Forma_Pago");

                    b.HasIndex("InmuebleId");

                    b.HasIndex("InmuebleId_Inmueble")
                        .IsUnique()
                        .HasFilter("[InmuebleId_Inmueble] IS NOT NULL");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Inmueble", b =>
                {
                    b.HasOne("SistemaVentasBienes.Models.Tipo_Inmueble", "Tipo_Inmueble")
                        .WithMany()
                        .HasForeignKey("TipoInmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo_Inmueble");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Venta", b =>
                {
                    b.HasOne("SistemaVentasBienes.Models.Condicion", "Condicion")
                        .WithMany()
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVentasBienes.Models.Forma_Pago", "Forma_Pago")
                        .WithMany()
                        .HasForeignKey("Forma_PagoId_Forma_Pago");

                    b.HasOne("SistemaVentasBienes.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("InmuebleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaVentasBienes.Models.Inmueble", "Inmueble")
                        .WithOne("Venta")
                        .HasForeignKey("SistemaVentasBienes.Models.Venta", "InmuebleId_Inmueble");

                    b.Navigation("Cliente");

                    b.Navigation("Condicion");

                    b.Navigation("Forma_Pago");

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("SistemaVentasBienes.Models.Inmueble", b =>
                {
                    b.Navigation("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
